server:
  port: 8090
  servlet:
    context-path: /nova
spring:
  application:
      name: novaRestService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: d0eee00b2fd50e3d22cbdff533f4ef0d24f7011c8d8bb0ad96bf056afa3404e2
    url: jdbc:postgresql://ec2-50-17-90-177.compute-1.amazonaws.com:5432/d6l3bl7ed3iu7o
    username: ukmjzyezgyoufd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
feign:
  client:
    config:
      NOVAMOCKSERVICE:
        connectTimeout: 10000
        readTimeout: 10000
NOVAMOCKSERVICE:
  ribbon:
    eureka:
      enabled: false
    listOfServers: https://suresh-nova-rest-mock-service.herokuapp.com/